name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    # Set up Python environment
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies
    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Create a ZIP archive of the project files for deployment
    - name: 'Prepare for Azure deployment'
      run: zip -r myfastapiapp.zip .

    # Deploy to Azure Web App using publish profile
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newtest1>'  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './myfastapiapp.zip'
